### ISSUE TITLE
TypeError: Cannot read property 'immediateLogs' of undefined

### ISSUE THREAD

**Issue by alexkushnarov** [usrz/javascript-karma-verbose-reporter#4]
Hey can you help me please with this issue I've updated karma-verbose-reporter to 0.0.4 and I have such error `TypeError: Cannot read property 'immediateLogs' of undefined` in the node_modules/karma-verbose-reporter/reporter.js:140:15 file

**Comment by pfumagalli** [comment]
It should be fixed in master. Please verify and I'll roll a new release if so.

**Comment by alexkushnarov** [comment]
Awesome Thx, you can make a new release.

**Comment by pfumagalli** [comment]
If you want, you can pick up 0.0.5 from NPM. Thanks for the report!

**Comment by alexkushnarov** [comment]
cool, welcome!
